### ISSUE TITLE
inconsistent vertical-align css causes misalignment

### ISSUE THREAD

**Issue by rsninja722** [FondationSTaBLFoundation/MOR2Issues#4]
the CSS for cs1xd3.online/RenderPublishedModule includes the following rule when cs1xd3.online/Code does not.

```css
img {
    vertical-align: middle;
    border-style: none;
}
```

this inconsistency will change the alignment of some images in modules that include images in [html](https://package.elm-lang.org/packages/MacCASOutreach/graphicsvg/latest/GraphicSVG#html) shapes when viewing forkable or shared versions of the module

adding the following rule to the CSS of cs1xd3.online/RenderPublishedModule will solve this
```css
foreignObject > img {
    vertical-align: unset;
}
```
